### ISSUE TITLE
 密码错误

### ISSUE THREAD

**Issue by kaka77** [veo/vercel_xss_platform#1]
大佬，我这边fork后，部署在vercel，Login.php页面使用默认密码bluelotus登录提示密码错误，config.php配置默认，用php -r '$salt="!KTMdg#^^I6Z!deIVR#SgpAI6qTN7oVl";$key="pass";$key=md5($salt.$key.$salt);$key=md5($salt.$key.$salt);$key=md5($salt.$key.$salt);echo $key;' 创建的Hash 替换也不行。。。

**Comment by veo** [comment]
> 大佬，我这边fork后，部署在vercel，Login.php页面使用默认密码bluelotus登录提示密码错误，config.php配置默认，用php -r '$salt="!KTMdg#^^I6Z!deIVR#SgpAI6qTN7oVl";$key="pass";$key=md5($salt.$key.$salt);$key=md5($salt.$key.$salt);$key=md5($salt.$key.$salt);echo $key;' 创建的Hash 替换也不行。。。

本地先调调。长期使用建议down下来在本地调试，并创建private项目进行部署，要不然你的密码public就被看到了

**Comment by kaka77** [comment]
> > 大佬，我这边fork后，部署在vercel，Login.php页面使用默认密码bluelotus登录提示密码错误，config.php配置默认，用php -r '$salt="!KTMdg#^^I6Z!deIVR#SgpAI6qTN7oVl";$key="pass";$key=md5($salt.$key.$salt);$key=md5($salt.$key.$salt);$key=md5($salt.$key.$salt);echo $key;' 创建的Hash 替换也不行。。。
> 
> 本地先调调。长期使用建议down下来在本地调试，并创建private项目进行部署，要不然你的密码public就被看到了

好的，谢谢建议。
